[package]
name = "riverbed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "crates/*"
]

[dependencies]
bevy = { version = "0.15" ,default-features = true, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "webgpu",
    "bevy_debug_stepping",
    "bevy_asset",
    "bevy_scene",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
]  }
bevy_dev_tools = "0.15"
bevy_atmosphere = "*"
confy = "*"
leafwing-input-manager = "*"
rand = "*"
rand_chacha = "*"
indexmap = "*"
itertools = "*"
vpsearch = "*"
parking_lot = "*"
crossbeam = "*"
csv = "*"
colorsys = "*"
anyhow = "*"
serde = "*"
strum = "*"
strum_macros = "*"
dashmap = "*"
futures-lite = "*"
array-macro = "*"
packed-uints = "*"
block-mesh = "*"
lazy_static = "*"
noise-algebra = "*"
regex = "*"
json5 = "*"
bevy_egui = "0.31"
riverbed_closest = { path = "crates/riverbed_closest", version = "*" }
binary-greedy-meshing = { path = "crates/binary-greedy-meshing", version = "*" }


[build-dependencies]
riverbed_block_def = { path = "crates/riverbed_block_def", version = "*" }

[profile.dev]
opt-level = 1
