/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const setup: () => void;
export const main: (a: number, b: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure12800_externref_shim: (a: number, b: number, c: any) => void;
export const closure12797_externref_shim: (a: number, b: number, c: any) => void;
export const closure12804_externref_shim: (a: number, b: number, c: any) => void;
export const closure12808_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8ea1d89af6d37d18: (a: number, b: number, c: number) => void;
export const closure35866_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf8cbced170bc5b29: (a: number, b: number) => void;
export const closure35854_externref_shim: (a: number, b: number, c: any) => void;
export const closure35857_externref_shim: (a: number, b: number, c: any) => void;
export const closure35860_externref_shim: (a: number, b: number, c: any) => void;
export const closure35878_externref_shim: (a: number, b: number, c: any) => void;
export const closure35881_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const closure35875_externref_shim: (a: number, b: number, c: any) => void;
export const closure35869_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h30c64cbd9f3f241c: (a: number, b: number) => void;
export const closure171277_externref_shim: (a: number, b: number, c: any) => void;
export const closure180308_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
